# Homework with Yelp reviews data

## Introduction

This assignment uses a small subset of the data from Kaggle's [Yelp Business Rating Prediction](https://www.kaggle.com/c/yelp-recsys-2013) competition.

**Description of the data:**

- **`yelp.csv`** contains the dataset. It is stored in the course repository (in the **`data`** directory), so there is no need to download anything from the Kaggle website.
- Each observation (row) in this dataset is a review of a particular business by a particular user.
- The **stars** column is the number of stars (1 through 5) assigned by the reviewer to the business. (Higher stars is better.) In other words, it is the rating of the business by the person who wrote the review.
- The **text** column is the text of the review.

**Goal:** Predict the star rating of a review using **only** the review text.

**Tip:** After each task, I recommend that you check the shape and the contents of your objects, to confirm that they match your expectations.

## Task 1

Read **`yelp.csv`** into a Pandas DataFrame and examine it.

In [1]:
import pandas as pd

data = pd.read_csv("../data/yelp.csv")

In [2]:
data.head()

,business_id,date,review_id,stars,text,type,user_id,cool,useful,funny
0,9yKzy9PApeiPPOUJEtnvkg,2011-01-26,fWKvX83p0-ka4JS3dc6E5A,5,My wife took me here on my birthday for breakf...,review,rLtl8ZkDX5vH5nAx9C3q5Q,2,5,0
1,ZRJwVLyzEJq1VAihDhYiow,2011-07-27,IjZ33sJrzXqU-0X6U8NwyA,5,I have no idea why some people give bad review...,review,0a2KyEL0d3Yb1V6aivbIuQ,0,0,0
2,6oRAC4uyJCsJl1X0WZpVSA,2012-06-14,IESLBzqUCLdSzSqm0eCSxQ,4,love the gyro plate. Rice is so good and I als...,review,0hT2KtfLiobPvh6cDC8JQg,0,1,0
3,_1QQZuf4zZOyFCvXc0o6Vg,2010-05-27,G-WvGaISbqqaMHlNnByodA,5,"Rosie, Dakota, and I LOVE Chaparral Dog Park!!...",review,uZetl9T0NcROGOyFfughhg,1,2,0
4,6ozycU1RpktNG2-1BroVtw,2012-01-05,1uJFq2r5QfJG_6ExMRCaGw,5,General Manager Scott Petello is a good egg!!!...,review,vYmM4KTsC8ZfQBg-j5MWkw,0,0,0

In [3]:
data.describe()

              stars          cool        useful         funny
count  10000.000000  10000.000000  10000.000000  10000.000000
mean       3.777500      0.876800      1.409300      0.701300
std        1.214636      2.067861      2.336647      1.907942
min        1.000000      0.000000      0.000000      0.000000
25%        3.000000      0.000000      0.000000      0.000000
50%        4.000000      0.000000      1.000000      0.000000
75%        5.000000      1.000000      2.000000      1.000000
max        5.000000     77.000000     76.000000     57.000000

In [4]:
data_star_1 = data[data['stars'] == 1][['stars','text', 'type', 'cool', 'useful']]
data_star_5 = data[data['stars'] == 5][['stars','text', 'type', 'cool', 'useful']]

In [5]:
data_star_1.count()

stars     749
text      749
type      749
cool      749
useful    749
dtype: int64

In [6]:
data_star_5.count()

stars     3337
text      3337
type      3337
cool      3337
useful    3337
dtype: int64

## Task 2

Create a new DataFrame that only contains the **5-star** and **1-star** reviews.

- **Hint:** [How do I apply multiple filter criteria to a pandas DataFrame?](https://www.youtube.com/watch?v=YPItfQ87qjM&list=PL5-da3qGB5ICCsgW1MxlZ0Hq8LL5U3u9y&index=9) explains how to do this.

In [7]:
data_15 = data[(data.stars == 1) | (data.stars == 5)]

In [8]:
data_15.sample(5)

,business_id,date,review_id,stars,text,type,user_id,cool,useful,funny
4665,IuAPYzf3NSyfyXYgT46YVA,2011-08-05,G_WnFnEd6H5grE3Dr9zb2g,5,Fried Squash blossoms! How do they come up wi...,review,Zwtx7FLZcK5F2P0-Tz8mHg,2,3,1
6542,4JOv7EnnfZ8fD3JunQQpyg,2009-01-27,YydJLd9f9e9JhwKjuZf-wg,5,Tempe Beach Park - such a gem in our landlocke...,review,fczQCSmaWF78toLEmb0Zsw,8,10,5
7614,-5rFC4EVrT-v8g1PSEf6Xg,2011-07-16,si-nMGBPO5Q8Axg0zgly0g,5,I was impressed with this place. I had the Mon...,review,0BfSTRcQpBTeNlx9SuAGWw,0,1,0
5962,xmjv8g356v8Qo55ICjG8rg,2011-03-11,4gElVx0ozu6OLz47Dcz4Bg,5,I love CK's. Their happy hour specials are gre...,review,GeGDZ02UfARKBRl7LqKZuA,0,1,0
8357,gUt-pPUpOVVhaCFC8-E4yQ,2011-03-27,Qv1jJdZftPlfJef45OX3GQ,5,Bomb ............................................,review,_tTNzjkD-pvWqSb-Ahw9Uw,0,0,0

## Task 3

Define X and y from the new DataFrame, and then split X and y into training and testing sets, using the **review text** as the only feature and the **star rating** as the response.

- **Hint:** Keep in mind that X should be a Pandas Series (not a DataFrame), since we will pass it to CountVectorizer in the task that follows.

In [9]:
X = data_15.text
y = data_15.stars

In [10]:
X.head()

0    My wife took me here on my birthday for breakf...
1    I have no idea why some people give bad review...
3    Rosie, Dakota, and I LOVE Chaparral Dog Park!!...
4    General Manager Scott Petello is a good egg!!!...
6    Drop what you're doing and drive here. After I...
Name: text, dtype: object

In [11]:
y.head()

0    5
1    5
3    5
4    5
6    5
Name: stars, dtype: int64

In [12]:
from sklearn.cross_validation import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2)

In [14]:
print(X_train.shape)
print(y_train.shape)

(3064,)
(3064,)

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

## Task 4

Use CountVectorizer to create **document-term matrices** from X_train and X_test.

In [16]:
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)
X_train_dtm

<3064x16530 sparse matrix of type '<type 'numpy.int64'>'
	with 234651 stored elements in Compressed Sparse Row format>

In [17]:
vect.get_feature_names()

[u'00',
 u'000',
 u'00am',
 u'00pm',
 u'01',
 u'02',
 u'03',
 u'03342',
 u'04',
 u'05',
 u'06',
 u'07',
 u'09',
 u'0l',
 u'10',
 u'100',
 u'1000',
 u'1000x',
 u'100s',
 u'100th',
 u'101',
 u'102',
 u'1030',
 u'105',
 u'108',
 u'109',
 u'10am',
 u'10ish',
 u'10min',
 u'10mins',
 u'10minutes',
 u'10pm',
 u'10th',
 u'10x',
 u'10yo',
 u'11',
 u'110',
 u'112',
 u'115',
 u'115th',
 u'116',
 u'118',
 u'11a',
 u'11am',
 u'12',
 u'120',
 u'128i',
 u'129',
 u'12am',
 u'12oz',
 u'12pm',
 u'12th',
 u'13',
 u'1300',
 u'13331',
 u'13th',
 u'14',
 u'140',
 u'147',
 u'14lbs',
 u'15',
 u'150',
 u'1500',
 u'150mm',
 u'15am',
 u'15mins',
 u'15th',
 u'16',
 u'160',
 u'165',
 u'16th',
 u'17',
 u'175',
 u'17th',
 u'18',
 u'180',
 u'1800',
 u'1895',
 u'18th',
 u'19',
 u'1900',
 u'1913',
 u'1940',
 u'1955',
 u'1956',
 u'1960',
 u'1961',
 u'1968',
 u'1970',
 u'1980',
 u'1980s',
 u'1987',
 u'1990',
 u'1990s',
 u'1995',
 u'1996',
 u'1998',
 u'1999',
 u'19th',
 u'1cent',
 u'1k',
 u'1p',
 u'1pm',
 u'1st',
 u'20',
 u'200',
 u'2002',
 u'2003',
 u'2005',
 u'2006',
 u'2007',
 u'2008',
 u'2009',
 u'2010',
 u'2011',
 u'2012',
 u'202',
 u'20miles',
 u'20min',
 u'20minutes',
 u'20pm',
 u'20s',
 u'20th',
 u'20x',
 u'21',
 u'21st',
 u'22',
 u'220',
 u'2240',
 u'22oz',
 u'23',
 u'24',
 u'24hrs',
 u'24st',
 u'24th',
 u'25',
 u'250',
 u'25b',
 u'25min',
 u'25th',
 u'26',
 u'260',
 u'2600',
 u'2608',
 u'26th',
 u'27',
 u'272',
 u'28',
 u'29',
 u'29th',
 u'2am',
 u'2mbps',
 u'2nd',
 u'2pm',
 u'2rd',
 u'2x',
 u'30',
 u'300',
 u'30am',
 u'30p',
 u'30pm',
 u'30s',
 u'30th',
 u'31',
 u'316',
 u'32',
 u'33',
 u'33rd',
 u'34',
 u'34th',
 u'35',
 u'350ib',
 u'35c',
 u'35th',
 u'37',
 u'370',
 u'38',
 u'38th',
 u'39',
 u'3am',
 u'3d',
 u'3g',
 u'3p',
 u'3pm',
 u'3rd',
 u'3x',
 u'40',
 u'400',
 u'4000',
 u'40lm',
 u'40min',
 u'40th',
 u'41',
 u'4113416766',
 u'42',
 u'43',
 u'44',
 u'4458',
 u'44th',
 u'45',
 u'453990',
 u'45min',
 u'45pm',
 u'46',
 u'4655',
 u'48',
 u'480',
 u'48th',
 u'49',
 u'490',
 u'4b',
 u'4cxbhzxxtmexf9krjmfviq',
 u'4hr',
 u'4ish',
 u'4pm',
 u'4th',
 u'4x6',
 u'50',
 u'500',
 u'50cents',
 u'50lm',
 u'50s',
 u'51',
 u'51pm',
 u'52',
 u'5231',
 u'53',
 u'54',
 u'547',
 u'55',
 u'56',
 u'57',
 u'59',
 u'59th',
 u'5k',
 u'5min',
 u'5pm',
 u'5stars',
 u'5th',
 u'5yo',
 u'60',
 u'600',
 u'6000',
 u'602',
 u'61',
 u'61st',
 u'62010',
 u'623',
 u'630am',
 u'64',
 u'64th',
 u'65',
 u'66',
 u'6600',
 u'68',
 u'69',
 u'6am',
 u'6pm',
 u'6th',
 u'70',
 u'700',
 u'70s',
 u'71',
 u'74th',
 u'75',
 u'750',
 u'755891987',
 u'76',
 u'7807',
 u'79',
 u'7am',
 u'7pm',
 u'7th',
 u'80',
 u'800',
 u'80s',
 u'81',
 u'832',
 u'83rd',
 u'85',
 u'85154658',
 u'85340',
 u'88',
 u'89',
 u'8am',
 u'8pm',
 u'8th',
 u'8v',
 u'8x10',
 u'8yo',
 u'90',
 u'9000',
 u'90s',
 u'91',
 u'911',
 u'92nd',
 u'95',
 u'96',
 u'977',
 u'98',
 u'99',
 u'9999',
 u'9am',
 u'9oz',
 u'9pm',
 u'9th',
 u'9year',
 u'______',
 u'_______________',
 u'_gyib8ea4hdfylss17zc_g',
 u'a1',
 u'a2',
 u'aa',
 u'aaa',
 u'aaammmazzing',
 u'aaron',
 u'ab',
 u'aback',
 u'abandoned',
 u'abandoning',
 u'abba',
 u'abbreviate',
 u'abbreviated',
 u'abc',
 u'abdomen',
 u'abhor',
 u'abiding',
 u'abilities',
 u'ability',
 u'able',
 u'abodoba',
 u'abou',
 u'abound',
 u'about',
 u'above',
 u'abrasion',
 u'abroad',
 u'abrupt',
 u'absence',
 u'absent',
 u'absinthe',
 u'absoloutely',
 u'absolute',
 u'absolutely',
 u'absolutley',
 u'absolutly',
 u'abstract',
 u'absurd',
 u'abuelo',
 u'abundance',
 u'abundant',
 u'abysmal',
 u'ac',
 u'academy',
 u'acai',
 u'acapulco',
 u'accent',
 u'accented',
 u'accents',
 u'accept',
 u'acceptable',
 u'accepted',
 u'accepting',
 u'accepts',
 u'access',
 u'accessible',
 u'accessories',
 u'accessorize',
 u'accessory',
 u'accident',
 u'accidental',
 u'accidentally',
 u'accidently',
 u'acclaimed',
 u'accolades',
 u'accommodate',
 u'accommodated',
 u'accommodates',
 u'accommodating',
 u'accommodation',
 u'accommodations',
 u'accomodate',
 u'accomodated',
 u'accomodating',
 u'accompanied',
 u'accompaniment',
 u'accompany',
 u'accompanying',
 u'accomplish',
 u'accomplished',
 u'accomplishment',
 u'according',
 u'accordingly',
 u'account',
 u'accountable',
 u'accounts',
 u'accoutrement',
 u'accredited',
 u'accross',
 u'accurate',
 u'accurately',
 u'accusation',
 u'accused',
 u'accustomed',
 u'ace',
 u'ache',
 u'aches',
 u'achieve',
 u'achievement',
 u'acid',
 u'acidic',
 u'acknowledge',
 u'acknowledged',
 u'acknowledging',
 u'acne',
 u'acoustic',
 u'acoustics',
 u'acquaintance',
 u'acquired',
 u'acres',
 u'acrid',
 u'acrimonious',
 u'across',
 u'acrylics',
 u'act',
 u'acted',
 u'acting',
 u'action',
 u'actions',
 u'activation',
 u'active',
 u'actively',
 u'activities',
 u'activity',
 u'actor',
 u'actors',
 u'acts',
 u'actual',
 u'actually',
 u'actualy',
 u'actully',
 u'acute',
 u'acy',
 u'ad',
 u'adage',
 u'adam',
 u'adamant',
 u'adapter',
 u'add',
 u'addd',
 u'added',
 u'addict',
 u'addicted',
 u'addicting',
 u'addictingly',
 u'addiction',
 u'addictionovercome',
 u'addictive',
 u'adding',
 u'addition',
 u'additional',
 u'additionally',
 u'additions',
 u'address',
 u'addressed',
 u'adds',
 u'ade',
 u'adelman',
 u'adequate',
 u'adequately',
 u'adios',
 u'adjacent',
 u'adjoining',
 u'adjust',
 u'adjusted',
 u'adjustment',
 u'adjustments',
 u'administrative',
 u'admire',
 u'admired',
 u'admiring',
 u'admission',
 u'admit',
 u'admits',
 u'admitted',
 u'admittedly',
 u'admonishment',
 u'ado',
 u'adobe',
 u'adobo',
 u'adopt',
 u'adoption',
 u'adorable',
 u'adoration',
 u'adore',
 u'adorned',
 u'adovada',
 u'adrian',
 u'adrienne',
 u'ads',
 u'adult',
 u'adulthood',
 u'adults',
 u'advance',
 u'advanced',
 u'advancing',
 u'advantage',
 u'adventure',
 u'adventures',
 u'adventurous',
 u'adverse',
 u'adversity',
 u'advertise',
 u'advertised',
 u'advertisements',
 u'advertising',
 u'advice',
 u'advise',
 u'advised',
 u'advisor',
 u'advisors',
 u'advocate',
 u'advocated',
 u'aeg',
 u'aerobic',
 u'aerobics',
 u'aerosol',
 u'aesthetically',
 u'aesthetics',
 u'affair',
 u'affect',
 u'affected',
 u'affects',
 u'afficianados',
 u'affiliated',
 u'affiliates',
 u'affiliation',
 u'affliction',
 u'affluent',
 u'afforadable',
 u'afford',
 u'affordable',
 u'aficionado',
 u'aficionados',
 u'afloat',
 u'aforementioned',
 u'afoul',
 u'afraid',
 u'africa',
 u'after',
 u'afterall',
 u'afterglow',
 u'afternoon',
 u'afternoons',
 u'aftertaste',
 u'afterthought',
 u'afterward',
 u'afterwards',
 u'again',
 u'against',
 u'agape',
 u'agave',
 u'age',
 u'aged',
 u'agency',
 u'agent',
 u'agents',
 u'ages',
 u'aggressive',
 u'aging',
 u'agitated',
 u'ago',
 u'agonizing',
 u'agree',
 u'agreeably',
 u'agreed',
 u'agreeing',
 u'agrees',
 u'agua',
 u'aguas',
 u'aguila',
 u'ah',
 u'ahead',
 u'ahem',
 u'ahh',
 u'ahhh',
 u'ahhhh',
 u'ahhhhh',
 u'ahhhhhh',
 u'ahi',
 u'ahwahtukee',
 u'ahwatukee',
 u'aid',
 u'aiello',
 u'aiko',
 u'aim',
 u'aimed',
 u'aimlessly',
 u'ain',
 u'aint',
 u'aioli',
 u'aiptasia',
 u'air',
 u'airfair',
 u'airfare',
 u'airline',
 u'airlines',
 u'airpark',
 u'airplane',
 u'airport',
 u'airports',
 u'airwarys',
 u'airways',
 u'airy',
 u'aisha',
 u'aisle',
 u'aisles',
 u'aj',
 u'ajar',
 u'aji',
 u'ajo',
 u'ajs',
 u'aka',
 u'aki',
 u'aknowledging',
 u'al',
 u'ala',
 u'alabama',
 u'aladdin',
 u'alain',
 u'alameda',
 u'alan',
 u'alarmed',
 u'alas',
 u'alaska',
 u'alaskan',
 u'alaus',
 u'albacore',
 u'albeit',
 u'alber',
 u'albertsons',
 u'album',
 u'albums',
 u'alcatraz',
 u'alcohol',
 u'alcoholic',
 u'ale',
 u'alert',
 u'alerting',
 u'ales',
 u'alessia',
 u'alex',
 u'alexandra',
 u'alfred',
 u'alfredo',
 u'algae',
 u'ali',
 u'alice',
 u'alienate',
 u'alienated',
 u'aliens',
 u'alike',
 u'alittle',
 u'alive',
 u'all',
 u'allegiant',
 u'allen',
 u'allende',
 u'allergic',
 u'allergies',
 u'allergy',
 u'allesia',
 u'alleviated',
 u'alley',
 u'alligator',
 u'allocating',
 u'allot',
 u'alloted',
 u'allotted',
 u'allow',
 u'allowable',
 u'allowance',
 u'allowed',
 u'allowing',
 u'allows',
 u'alluring',
 u'almond',
 u'almonds',
 u'almost',
 u'aloe',
 u'alofts',
 u'aloha',
 u'alone',
 u'along',
 u'alongside',
 u'alons',
 u'aloo',
 u'aloof',
 u'alot',
 u'aloud',
 u'alp',
 u'alphagraphics',
 u'alread',
 u'already',
 u'alright',
 u'also',
 u'alteration',
 u'alterations',
 u'altercation',
 u'altered',
 u'altering',
 u'alternately',
 u'alternative',
 u'alternatives',
 u'although',
 u'altic',
 u'alums',
 u'alvadora',
 u'always',
 u'am',
 u'ama',
 u'amaaaaazing',
 u'amaazing',
 u'amalfi',
 u'amanda',
 u'amaretti',
 u'amaretto',
 u'amarillo',
 u'amateur',
 u'amaze',
 u'amazeballs',
 u'amazed',
 u'amazement',
 u'amazes',
 u'amazing',
 u'amazingly',
 u'amazingness',
 u'amazon',
 u'amazzzzzzing',
 u'ambassador',
 u'amber',
 u'ambiance',
 u'ambience',
 u'ambient',
 u'ambrosia',
 u'ambrosio',
 u'ambulance',
 u'amc',
 u'amenable',
 u'amend',
 u'amendment',
 u'amenities',
 u'amenity',
 u'america',
 u'american',
 u'americana',
 u'americanized',
 u'americano',
 u'americanos',
 u'americans',
 u'amerizona',
 u'ami',
 u'amicable',
 u'amid',
 u'amidst',
 u'amin',
 u'amish',
 u'ammo',
 u'amomi',
 u'among',
 u'amongst',
 u'amonst',
 u'amore',
 u'amount',
 u'amounts',
 u'amp',
 u'ample',
 u'ampm',
 u'amsterdam',
 u'amtrack',
 u'amuse',
 u'amused',
 u'amusement',
 u'amusing',
 u'amy',
 u'an',
 u'anaheim',
 u'anal',
 u'analogy',
 u'analysis',
 u'analyze',
 u'ancho',
 u'anchor',
 u'anchored',
 u'anchors',
 u'anchovies',
 u'ancillary',
 u'and',
 u'andouille',
 u'andrea',
 u'andrew',
 u'andy',
 u'anecdotes',
 u'anemic',
 u'anew',
 u'angel',
 u'angela',
 u'angeles',
 u'angello',
 u'angels',
 u'anger',
 u'angie',
 u'angle',
 u'angler',
 u'angles',
 u'angry',
 u'angst',
 u'anibal',
 u'animal',
 u'animals',
 u'animated',
 u'animatronics',
 u'anise',
 u'aniston',
 u'ankles',
 u'ann',
 u'anne',
 u'annette',
 u'annie',
 u'anniversary',
 u'announced',
 u'annoyance',
 u'annoyed',
 u'annoying',
 u'annual',
 u'another',
 u'ans',
 u'answer',
 u'answered',
 u'answering',
 u'answers',
 u'antchiladas',
 u'anthem',
 u'anthony',
 u'anti',
 u'anticipate',
 u'anticipated',
 u'anticipating',
 u'antipasti',
 u'antipasto',
 u'antique',
 u'antiques',
 u'antiquing',
 u'antiseptic',
 u'antithesis',
 u'antler',
 u'antonio',
 u'antono',
 u'ants',
 u'anxiety',
 u'anxious',
 u'anxiously',
 u'any',
 u'anybody',
 u'anyday',
 u'anyhoo',
 u'anyhow',
 u'anymore',
 u'anyone',
 u'anything',
 u'anythings',
 u'anytime',
 u'anyway',
 u'anyways',
 u'anywhere',
 u'anywho',
 u'ao',
 u'ap',
 u'apache',
 u'apart',
 u'apartment',
 u'apartments',
 u'apologetic',
 u'apologetically',
 u'apologies',
 u'apologists',
 u'apologize',
 u'apologized',
 u'apologizing',
 u'apology',
 u'apostles',
 u'app',
 u'appalachians',
 u'appaled',
 u'appalled',
 u'appalling',
 u'apparantly',
 u'apparel',
 u'apparently',
 u'apparitions',
 u'appauled',
 u'appauling',
 u'appeal',
 u'appealed',
 u'appealing',
 u'appeals',
 u'appear',
 u'appearance',
 u'appearances',
 u'appeared',
 u'appears',
 u'appeasing',
 u'appetit',
 u'appetite',
 u'appetito',
 u'appetizer',
 u'appetizers',
 u'appetizing',
 u'appitizer',
 u'applaud',
 u'applause',
 u'apple',
 u'applebee',
 u'applebees',
 u'apples',
 u'appletini',
 u'appletinis',
 u'applewood',
 u'appliances',
 u'applied',
 u'applies',
 u'apply',
 u'applying',
 u'appoinmtnt',
 u'appointed',
 u'appointment',
 u'appointments',
 u'appraisal',
 u'appraiser',
 u'appreciate',
 u'appreciated',
 u'appreciation',
 u'appreciative',
 u'apprehensive',
 u'approach',
 u'approachable',
 u'approached',
 u'approaches',
 u'approaching',
 u'appropriate',
 u'appropriately',
 u'approval',
 u'approx',
 u'approximate',
 u'approximately',
 u'apps',
 u'appt',
 u'appy',
 u'apricot',
 u'april',
 u'apron',
 u'apt',
 u'aqua',
 u'aquarium',
 u'arbol',
 u'arborio',
 u'arbuckle',
 u'arcade',
 u'arcadia',
 u'arcane',
 u'arches',
 u'architect',
 u'architecture',
 u'archive',
 u'archway',
 u'are',
 u'area',
 u'areas',
 u'aren',
 u'arena',
 u'arent',
 u'argentine',
 u'argue',
 u'argued',
 u'argues',
 u'arguing',
 u'argumentative',
 u'argyle',
 u'arigato',
 u'arise',
 u'arises',
 u'arizona',
 u'arizonan',
 u'arizonans',
 u'arizonian',
 u'arizonians',
 u'arkansas',
 u'arlecchino',
 u'arlin',
 u'arm',
 ...]

In [18]:
#vect.fit(X_test)
X_test_dtm = vect.transform(X_test)
X_test_dtm

<1022x16530 sparse matrix of type '<type 'numpy.int64'>'
	with 79710 stored elements in Compressed Sparse Row format>

# Task 5
Use Multinomial Naive Bayes to predict the star rating for the reviews in the testing set, and then calculate the accuracy and print the confusion matrix.

- **Hint:** [Evaluating a classification](https://github.com/justmarkham/scikit-learn-videos/blob/master/09_classification_metrics.ipynb) model explains how to interpret both classification accuracy and the confusion matrix.

In [19]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [20]:
# train the model using X_train_dtm (timing it with an IPython "magic command")
%time nb.fit(X_train_dtm, y_train)

CPU times: user 5.65 ms, sys: 1.7 ms, total: 7.35 ms
Wall time: 10.1 ms

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [21]:
# make class predictions for X_test_dtm
y_pred_class = nb.predict(X_test_dtm)

In [22]:
y_pred_class

array([5, 5, 5, ..., 5, 1, 5])

In [23]:
# calculate the model accuracy
from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred_class))

0.92759295499

In [24]:
# Confusion matrix
print(metrics.confusion_matrix(y_test, y_pred_class))

[[128  61]
 [ 13 820]]

In [25]:
print("True: ", y_test.values[10:30])
print("Pred: ", y_pred_class[10:30])

('True: ', array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 5, 1, 1, 5, 5, 5, 5]))
('Pred: ', array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 5, 5, 5, 5, 5, 5, 5]))

## Task 6 (Challenge)

Calculate the **null accuracy**, which is the classification accuracy that could be achieved by always predicting the most frequent class.

- **Hint:** [Evaluating a classification model](https://github.com/justmarkham/scikit-learn-videos/blob/master/09_classification_metrics.ipynb) explains null accuracy and demonstrates two ways to calculate it, though only one of those ways will work in this case. Alternatively, you can come up with your own method to calculate null accuracy!

In [26]:
sy_class = pd.Series(y_test)

In [27]:
sy_class.value_counts()

5    833
1    189
dtype: int64

In [28]:
sy_class

5646    5
5573    5
2747    5
201     5
8406    5
9866    5
1177    5
1291    1
6724    5
1288    5
7800    5
1749    5
74      5
8143    5
7569    5
5240    5
5761    5
8025    5
334     5
9178    5
8697    5
4445    5
2726    1
6002    5
9351    1
1227    1
9667    5
266     5
9212    5
4106    5
       ..
3019    5
8605    5
2006    5
2306    5
2615    1
8233    1
2297    1
7413    1
9082    5
7377    1
1747    1
1116    1
4034    5
754     5
870     5
8642    1
2129    5
8072    1
4962    5
1253    5
145     5
9782    5
4       5
6984    5
8270    1
101     5
1458    5
9474    5
8758    1
6378    5
Name: stars, dtype: int64

In [29]:
print(1-sy_class.mean())

-3.2602739726

## Task 7 (Challenge)

Browse through the review text of some of the **false positives** and **false negatives**. Based on your knowledge of how Naive Bayes works, do you have any ideas about why the model is incorrectly classifying these reviews?

- **Hint:** [Evaluating a classification model](https://github.com/justmarkham/scikit-learn-videos/blob/master/09_classification_metrics.ipynb) explains the definitions of "false positives" and "false negatives".
- **Hint:** Think about what a false positive means in this context, and what a false negative means in this context. What has scikit-learn defined as the "positive class"?

In [30]:
print(X_test.head())
print(y_test.head())

5646    So I was introduced to this station about 6 mo...
5573    Fair and honest prices.  Friends and I have be...
2747    Better than Starbucks anyday! \nThe staff enco...
201     A group of us from the IVAA Summit went to Zin...
8406    went down to Scottsdale for Spring Training (G...
Name: text, dtype: object
5646    5
5573    5
2747    5
201     5
8406    5
Name: stars, dtype: int64

In [31]:
sy_pred_class = pd.Series(y_pred_class)
sy_pred_class.head()

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [32]:
new_df = pd.DataFrame({'text': X_test, 'True': y_test, 'Pred': y_pred_class})

In [33]:
new_df[new_df['Pred'] > new_df['True']]

      Pred  True                                               text
9351     5     1  Dr. Pierrend is ok, he will write prescription...
1227     5     1  This place was messy and loud.  The food reall...
9296     5     1  My boyfriend and I tried this place last year ...
1406     5     1  From my door, it's a five minute stroll throug...
6229     5     1  Forget the yogurt and the berry berry bad serv...
7803     5     1  I'm sad to report that we dined here for lunch...
4562     5     1  despite it's billing as the 'largest thrift st...
6977     5     1  Had to eat here with coworkers for lunch today...
5814     5     1  I do enjoy a good bowl of Pho.   This was -not...
666      5     1  I waited 45min and ended up with a tiny gross ...
765      5     1  I am not a fan of this place. I like to try to...
4595     5     1  I have been here once for lunch and sat outsid...
208      5     1  Wednesday 7pm.  This place is your average ove...
7845     5     1  They wouldn't honor pet co's online sale price...
6146     5     1  I came to the restaurant specifically because ...
4031     5     1  One star would be giving it a holiday gift!\n\...
8507     5     1                       This location is now closed.
35       5     1  I've eaten here many times, but none as bad as...
7631     5     1  this is a business located in the fry's grocer...
8626     5     1                     sslowest drive through ever!!!
6344     5     1  Their amazing prices are instantly countered b...
3461     5     1  I will make this real easy for you. \n\nJust g...
753      5     1  I went today to meet my daughter for lunch.  W...
2060     5     1              This place is closed.  Good riddance.
9794     5     1  All I have to say is what you see on the menu ...
9640     5     1  Went here one night with a group of friends. T...
9272     5     1  I enjoy falafels and my boyfriend really likes...
1418     5     1  So, what kind of place serves chicken fingers ...
4766     5     1                                     Very bad food!
6130     5     1  I can summarize this in one word.  YUCK!  We w...
...    ...   ...                                                ...
1608     5     1  The reviews were so good that my friend and I ...
8220     5     1  Maybe I ate at a different restaurant than the...
4842     5     1  My fiance and I tried the place because of a G...
9851     5     1  If you like sushi, go somewhere else. I was ex...
8441     5     1  NOTE: This review concerns the Roberto's on Un...
1721     5     1  This is the closest to a New York hipster styl...
6617     5     1  I just thought I'd post an update.  I planned ...
3440     5     1  I had such high expectaions after reading revi...
2490     5     1  Lazy Q CLOSED in 2010.  New Owners cleaned up ...
7586     5     1  It's been a few months since I've been here, a...
5955     5     1  I've now tried Thai Elephant three times.  My ...
7024     5     1  Received two more messages from "Iolanda" this...
3755     5     1  Have been going to LGO since 2003 and have alw...
3723     5     1  When owners/staff changed we kept hoping for t...
7720     5     1  Read al lthe hype, so decided to give Cyclo a ...
3392     5     1  I found Lisa G's while driving through phoenix...
6222     5     1  My mother always told me, if I didn't have any...
2594     5     1  My rating is based on the fact that as a veget...
6045     5     1  The cool name of the place is the only good th...
289      5     1  I'd say I've been to the Clubhouse a few times...
3125     5     1  Let me first say if I could have given 0 stars...
9846     5     1  NO.  Don't go. Don't do it.  This was my first...
9441     5     1  It was my Birthday and my wife, her mom, a dea...
3266     5     1  Absolutely awful... these guys have NO idea wh...
5950     5     1  I think chef Silvana Esparza first located the...
7447     5     1  Ok..I told Amanda that anyplace that serves be...
7956     5     1  What was Dunkin Donuts thinking when they took...
2615     5     1  Great in its day, now leaves a lot to be desir...
8233     5     1  Good prices but this please is honestly not wo...
2297     5     1  This is a sad excuse for a gay resort.  Sort o...

[61 rows x 3 columns]

In [34]:
new_df[new_df['Pred'] < new_df['True']]

      Pred  True                                               text
3052     1     5  When I met some friends for dinner at this res...
3999     1     5  TJ was there for me when my water heater broke...
6376     1     5     They have a mechanical bull.  Need I say more?
6512     1     5  When my youngest son graduated I took him to B...
3075     1     5                     Unfortunately Out of Business.
6050     1     5  I went to sears today to check on a layaway th...
7903     1     5  First, I'm sorry this review is lengthy, but i...
2444     1     5  EXCELLENT CUSTOMER SERVICE! \n\nEven with Happ...
3149     1     5  I was told to see Greg after a local shop diag...
6334     1     5  I came here today for a manicure and pedicure....
617      1     5  Tried going there for my 1st visit and they we...
696      1     5  This is the only auto repair place I've ever s...
2306     1     5  There are certain people in your life that you...

## Task 8 (Challenge)

Calculate which 10 tokens are the most predictive of **5-star reviews**, and which 10 tokens are the most predictive of **1-star reviews**.

- **Hint:** Naive Bayes automatically counts the number of times each token appears in each class, as well as the number of observations in each class. You can access these counts via the `feature_count_` and `class_count_` attributes of the Naive Bayes model object.

In [40]:
nb.feature_count_

array([[ 28.,   4.,   3., ...,   0.,   0.,   0.],
       [ 36.,   7.,   2., ...,   1.,   1.,   1.]])

In [42]:
nb.class_count_

array([  560.,  2504.])

In [43]:
X_train_tokens = vect.get_feature_names()
len(X_train_tokens)

16530

## Task 9 (Challenge)

Up to this point, we have framed this as a **binary classification problem** by only considering the 5-star and 1-star reviews. Now, let's repeat the model building process using all reviews, which makes this a **5-class classification problem**.

Here are the steps:

- Define X and y using the original DataFrame. (y should contain 5 different classes.)
- Split X and y into training and testing sets.
- Create document-term matrices using CountVectorizer.
- Calculate the testing accuracy of a Multinomial Naive Bayes model.
- Compare the testing accuracy with the null accuracy, and comment on the results.
- Print the confusion matrix, and comment on the results. (This [Stack Overflow answer](http://stackoverflow.com/a/30748053/1636598) explains how to read a multi-class confusion matrix.)
- Print the [classification report](http://scikit-learn.org/stable/modules/model_evaluation.html#classification-report), and comment on the results. If you are unfamiliar with the terminology it uses, research the terms, and then try to figure out how to calculate these metrics manually from the confusion matrix!